APP:
  DATASIZE: 1024
  INPUT: '../_data/testfiles/sherlock.txt'
  MAPPERS: 5
  REDUCERS: 5
  FUNCTION: word-count
  DEBUG: True
  HOST: localhost
  PORT: 27710

KEYVALSTORE:
  DATASIZE: 1024
  HOST: localhost
  PORT: 27700
  DB: ../kv_database.db

WORKERS:
  RAWDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/raw-data/'
  INTERIMDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/intermediate_data/'
  OUTPUTDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/output_data/'

MACHINES:
  - [localhost, 27720]
  - [localhost, 27730]
  - [localhost, 27740]
  - [localhost, 27750]

 