APP:
  DATASIZE: 1024
  INPUT: '../_data/testfiles/sherlocktest.txt'
  MAPPERS: 5
  REDUCERS: 5
  FUNCTION: word-count
  DEBUG: True
  HOST: localhost
  PORT: 27710

KEYVALSTORE:
  DATASIZE: 1024
  HOST: localhost
  PORT: 27700
  DB: ../kv_database.db

WORKERS:
  RAWDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/raw-data/'
  INTERIMDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/intermediate_data/'
  OUTPUTDATA: '/Users/main/Documents/repos/Cloud-Computing-Assignment2/_data/output_data/'

MAPPERS:
  - [localhost, 27720]

REDUCERS:
  - [localhost, 27820]
  - [localhost, 27830]
  - [localhost, 27840]
  - [localhost, 27850]

 